### ISSUE TITLE
bbox annotation format: Audacity Extended LabelTrack

### ISSUE THREAD

**Issue by NickleDave** [vocalpy/crowsetta#213]
I cannot find any public datasets using this format but want to document it as one that could be good to have:
https://manual.audacityteam.org/man/importing_and_exporting_labels.html#Extended_format_with_frequency_ranges

Basically, a bounding box instead of segments

The fact there are none publicly available suggests it's not widely used.  
Again, just documenting for future reference

**Comment by scikit-maad** [comment]
In ecoacoustics, people use Raven as well as Audacity to annotate there audio files. I'm pretty sure there are plenty of private datasets with this kind of anotations.
In our scikit-maad package, we added 2 examples. You can use it if you need.
https://github.com/scikit-maad/scikit-maad/tree/production/data
See my issue about this : https://github.com/vocalpy/crowsetta/issues/222

**Comment by NickleDave** [comment]
Excellent, thank you @shaupert @scikit-maad 

An initial implementation + test data are in this comment:
https://github.com/vocalpy/crowsetta/issues/222#issue-1587621330

Closing that issue as a duplicate of this but will start with that suggested implementation
